<?php include("header.php");?>

<div class="page-banner">
    <div class="container">
        <h2>blog details</h2>
    </div>
</div>

<section class="blog-details">
    <div class="container">
        <h2>Contemporizing the Use of <span>Marble</span> in Art and Design</h2>
        <img src="src/images/blogs/200104052506_blog_image.jpg" alt="">
       <p>The magnificence and elegance of marble has been embraced since eons. The popularity of marble began in ancient Rome and Greece, where white and off-white marble was used to construct a variety of structures, from hand-held sculptures to massive pillars.Splendid monuments, structures, sculptures and pieces of art from history are a testament to thewide usage of this versatile stone. Popular for its durability and resistance to weather conditions, structures made from marble that are a century old still look as pristine as the day they were crafted.</p>
       <p>Prized for its timeless elegance, marble continues to be a vital part of the development of civilisation. This exquisite metamorphic rock is known for its beauty, strength and durability.Naturally these are found in various colours suited for different places and choices. Each piece of marble differs from the other which gives it a unique appearance.Today, new and advanced technologies have augmented the number of ways in which artists and designers can experiment using marble, subsequently increasing the productivity and accessibility of marble based creations.Marble is now being used for a variety of structural and aesthetic purposes.</p>
       <p>Most widely used for flooring in homes and luxury spaces such as hotels, this evergreen materialadds a touch of sophistication to the mundane. Marble walls have been revered by the kings and queens in palaces and castles and thus add splendour to modern homes and hotels today. Undeniably stone, granite counters and sinks add to the visual appeal of the modern day kitchens and bathrooms. Being a strong, sturdy and long lasting material, this natural stone is now used to craft furniture to add a touch of luxury to wooden furnishing. It holds a reputation of being the ideal choice for luxury bathrooms. While marble flooring is a popular trend from the past, the addition of marble tubs is becoming a popular choice in luxury homes and spaces today. With regard to the trends,  Marble has pushed its limits to bring out and has curated the best of marble designs for their patrons, encouraging the utility of this stone in design. It, also, has been an inspiring journey for them collaborating with a vast number of artists, designers and architects.</p>
       <p>Throughout history sculptors have used marble as a medium to craft intricate pieces.Marble artworks have a significant place in major art movements and have been carved by some of the most famous sculptures in the world. Today, with the advancement of technology, Marble has created a niche collection of suchmarble artworks and continues to explore and experiment in newrealms of art and design.These artworks are now being widely used as decoration items as they are luxurious and appealing to the eye. The numerous variety of patterns in modern marble art pieces are gaining popularity in both home and hospitality décor which Marble seeks to augment to provide an exclusive range of products to choose from.</p>
       <p>Marble plays an instrumental role in bringing the world's most magnificent collection of marbles, stones and granite to India.With an expertise in using marble for art, architecture and design purposes, Marble is a one-stop destination for ideas and inspiration in the world of stones.The exclusive collection of Statuario, Michelangelo and Sodalite marbles are a favoured choice for wall cladding. Similarly, Blue, White Onyx, Ondulutu Onyx and semi precious stones like quartzagates are an ideal option for backlit installations, and as countertop material in dining tables and centre tables. Avant Garde textured stone like Statuario Moonface, Grego Venezia, Snow White, Mocha Cream Leather are often used on the façade and exterior garden space.</p>
       <p>Widening their horizon from the domain of architecture and design, the brand is also known to have crafted marble masterpieces that are a true reflection of modern art. Recently the brand crafted suave marble trophies for AD 100 award ceremony. They are also known to have sculpted beautiful figures with incredible attention to detail and refined chiselling techniques.The brand has revived the significanceof this natural stone, with a contemporary perspective towards art and design whilst making the most of its versatility in art, architecture and design. Presented with such opportunities, aspires to bring more creativity to their collections as they believe in the great potential of this material in the coming days.</p>
    </div>
</section>

<?php include("footer.php");?>