<?php include("header.php");?>

<div class="page-banner">
    <div class="container">
        <h2>blog details</h2>
    </div>
</div>

<section class="blog-details">
    <div class="container">
        <h2>Tips on how to add colourful <span>marbles</span> to your design</h2>
        <img src="src/images/blogs/210217130036_blog_image.jpg" alt="">
        <p>Coloured stones and marble add a lot of colour to spaces and bring in patterns and textural variety. From a pop of vibrancy to earthy monotones, coloured stones fit into every design theme adding luxurious details to any space. Some of the elements you can add coloured stones to within a home are</p>
        <h3>Flooring :</h3>
        <p>Flooring is a great space to explore the application of stone. Using coloured stones with patterns and textures is a great way to bring in colour without jarring.  Coloured stone can either be used throughout the floor plate or as highlights placed between subtle flooring tiles. Coloured stone can be used in various indoor and outdoor spaces just as quickly and efficiently.</p>
        <h3>Wall finishes :</h3>
        <p>Walls provide a perfect canvas for design and bring in incredible opportunity to reflect style. Coloured stones can be used as slabs to create walls that become the central focus of a room or as cladding to add textural details. A combination of the two also creates exciting details. In outdoor spaces, coloured stones can be used to add vibrancy to the space. The waste generated by coloured stones during the cladding process could also be used as artwork or murals in balcony, terraces or garden areas.</p>
        <h3>Shelves and storage :</h3>
        <p>Within interiors, coloured stones help create statement luxury pieces such as tabletops, kitchen finishes, shelves and storage shutters. The use of precious or rare stones as a tabletop can create a stunning dining table that becomes the centrepiece of a dining area. Using coloured stones on shutters or as shelves is a great way to add patterns and textures to interior finishes.</p>
        <p>Coloured stones help add a sense of style through the varied colours, patterns and textures they offer. If picked out with attention to detail, they provide a wide variety that can bring it elegance and character into any space. Since they’re incredibly versatile in application, the opportunities to use coloured stone has no bounds.</p>
    </div>
</section>

<?php include("footer.php");?>